export const CONFIG = {
  PUSHER_ID: process.env.VITE_REACT_APP_PUSHER_ID,
  PUSHER_KEY: process.env.VITE_REACT_APP_PUSHER_KEY,
  PUSHER_SECRET: process.env.VITE_REACT_APP_PUSHER_SECRET,
  PUSHER_CLUSTER: process.env.VITE_REACT_APP_PUSHER_CLUSTER,
};
